### ISSUE TITLE
no index.js

### ISSUE THREAD

**Issue by SuneR-what** [remos/discord-queue-bot#2]
Hey,
After installing the package, I cant find any index.js fil. Is it me that dont understand how it works, or is it missing?
I get the: Error: Cannot find module 'C:\Users\XXX\Desktop\discord-queue-bot-master\dist\index.js'. Please verify that the package.json has a valid "main" entry

But there is no index,js to be found anywhere in the package? Should I write that my self? :S

Thanks in advance
Sune

**Comment by remos** [comment]
Sorry about the huge delay

It looks like you might not have installed it using npm or yarn and rather checked out the repo itself. In which case you'll need to build it locally first (by running `yarn` then `yarn build`)

Otherwise you should be able to use it as a global cli by using `yarn global add discord-queue-bot` and running with `yarn discord-queue-bot` or in another package by using `yarn add discord-queue-bot` (check the README.md) 

Hope this helps
